[ptr-admin-nginx-abuse]
enabled = true
filter = ptr-admin-nginx-abuse
logpath = /var/log/nginx/access.log
backend = auto
port = 80,443
banaction = ptr-docker
findtime = 10m
maxretry = 6
bantime = 1h
bantime.increment = true
bantime.maxtime = 7d
